/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF , MeshDistortMaterial } from '@react-three/drei'
import diamond from './diamond.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(diamond)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh  geometry={nodes.Cylinder.geometry} >
      <MeshDistortMaterial
     envMap={null}
     reflectivity={0.9}
     metalness={1}
     
     refractionRatio={0.98}
     color={"#CCFFFD"}
    attach="material"
    distort={0} // Strength, 0 disables the effect (default=1)
    speed={1} // Speed (default=1)
    roughness={1}
  />
        </mesh>
    </group>
  )
}

useGLTF.preload(diamond)
